#!/bin/bash

# Kernels 2.6.16 and newer provide a mechanism to have the kernel 
# drop the page cache and/or inode and dentry caches on command, 
# which can help free up a lot of memory.

# Running sync first flushes dirty objects out to disk, allowing
# us to free up more memory.

set -x

sudo sync
sudo sync
sudo sync

# To free pagecache:
# echo 1 > /proc/sys/vm/drop_caches

# To free dentries and inodes:
# echo 2 > /proc/sys/vm/drop_caches

# To free pagecache, dentries and inodes: 
sudo bash -c '/bin/echo 3 > /proc/sys/vm/drop_caches'

